<?php

/**
 * BaseEmpContractNew
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property int             $emp_number                          Type: integer(4), primary key
 * @property int             $emp_contract_number                 Type: integer(4), primary key
 * @property string          $emp_contract_start_date             Type: timestamp(25), Timestamp in ISO-8601 format (YYYY-MM-DD HH:MI:SS)
 * @property string          $emp_contract_end_date               Type: timestamp(25), Timestamp in ISO-8601 format (YYYY-MM-DD HH:MI:SS)
 * @property string          $keterangan                          Type: string
 * @property Employee        $Employee                            
 *  
 * @method int               getEmpNumber()                       Type: integer(4), primary key
 * @method int               getEmpContractNumber()               Type: integer(4), primary key
 * @method string            getEmpContractStartDate()            Type: timestamp(25), Timestamp in ISO-8601 format (YYYY-MM-DD HH:MI:SS)
 * @method string            getEmpContractEndDate()              Type: timestamp(25), Timestamp in ISO-8601 format (YYYY-MM-DD HH:MI:SS)
 * @method string            getKeterangan()                      Type: string
 * @method Employee          getEmployee()                        
 *  
 * @method EmpContractNew    setEmpNumber(int $val)               Type: integer(4), primary key
 * @method EmpContractNew    setEmpContractNumber(int $val)       Type: integer(4), primary key
 * @method EmpContractNew    setEmpContractStartDate(string $val) Type: timestamp(25), Timestamp in ISO-8601 format (YYYY-MM-DD HH:MI:SS)
 * @method EmpContractNew    setEmpContractEndDate(string $val)   Type: timestamp(25), Timestamp in ISO-8601 format (YYYY-MM-DD HH:MI:SS)
 * @method EmpContractNew    setKeterangan(string $val)           Type: string
 * @method EmpContractNew    setEmployee(Employee $val)           
 *  
 * @package    orangehrm
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEmpContractNew extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('hs_hr_emp_contract');
        $this->hasColumn('emp_number', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('emp_contract_number', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('emp_contract_start_date', 'timestamp', 25, array(
             'type' => 'timestamp',
             'length' => 25,
             ));
        $this->hasColumn('emp_contract_end_date', 'timestamp', 25, array(
             'type' => 'timestamp',
             'length' => 25,
             ));
        $this->hasColumn('keterangan', 'string', null, array(
             'type' => 'string',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Employee', array(
             'local' => 'emp_number',
             'foreign' => 'emp_number'));
    }
}