<?php

/**
 * BaseFingerspotRecord
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string            $sn                        Type: string(32), primary key
 * @property string            $scan_date                 Type: datetime, primary key, Date and time in ISO-8601 format (YYYY-MM-DD HH:MI)
 * @property string            $pin                       Type: string(30), primary key
 * @property int               $verifymode                Type: integer
 * @property int               $inoutmode                 Type: integer
 * @property int               $reserved                  Type: integer
 * @property int               $work_code                 Type: integer
 * @property string            $att_id                    Type: string(50)
 * @property Employee          $Employee                  
 *  
 * @method string              getSn()                    Type: string(32), primary key
 * @method string              getScanDate()              Type: datetime, primary key, Date and time in ISO-8601 format (YYYY-MM-DD HH:MI)
 * @method string              getPin()                   Type: string(30), primary key
 * @method int                 getVerifymode()            Type: integer
 * @method int                 getInoutmode()             Type: integer
 * @method int                 getReserved()              Type: integer
 * @method int                 getWorkCode()              Type: integer
 * @method string              getAttId()                 Type: string(50)
 * @method Employee            getEmployee()              
 *  
 * @method FingerspotRecord    setSn(string $val)         Type: string(32), primary key
 * @method FingerspotRecord    setScanDate(string $val)   Type: datetime, primary key, Date and time in ISO-8601 format (YYYY-MM-DD HH:MI)
 * @method FingerspotRecord    setPin(string $val)        Type: string(30), primary key
 * @method FingerspotRecord    setVerifymode(int $val)    Type: integer
 * @method FingerspotRecord    setInoutmode(int $val)     Type: integer
 * @method FingerspotRecord    setReserved(int $val)      Type: integer
 * @method FingerspotRecord    setWorkCode(int $val)      Type: integer
 * @method FingerspotRecord    setAttId(string $val)      Type: string(50)
 * @method FingerspotRecord    setEmployee(Employee $val) 
 *  
 * @package    orangehrm
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseFingerspotRecord extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ohrm_att_log');
        $this->hasColumn('sn', 'string', 32, array(
             'type' => 'string',
             'primary' => true,
             'length' => 32,
             ));
        $this->hasColumn('scan_date', 'datetime', null, array(
             'type' => 'datetime',
             'primary' => true,
             ));
        $this->hasColumn('pin', 'string', 30, array(
             'type' => 'string',
             'primary' => true,
             'length' => 30,
             ));
        $this->hasColumn('verifymode', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('inoutmode', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('reserved', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('work_code', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('att_id', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Employee', array(
             'local' => 'pin',
             'foreign' => 'pin'));
    }
}