<?php

/**
 * BaseFingerspotDevices
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property int                $No                        Type: integer, primary key
 * @property string             $server_IP                 Type: string(255)
 * @property string             $server_port               Type: string(255)
 * @property string             $device_sn                 Type: string(255)
 *  
 * @method int                  getNo()                    Type: integer, primary key
 * @method string               getServerIp()              Type: string(255)
 * @method string               getServerPort()            Type: string(255)
 * @method string               getDeviceSn()              Type: string(255)
 *  
 * @method FingerspotDevices    setNo(int $val)            Type: integer, primary key
 * @method FingerspotDevices    setServerIp(string $val)   Type: string(255)
 * @method FingerspotDevices    setServerPort(string $val) Type: string(255)
 * @method FingerspotDevices    setDeviceSn(string $val)   Type: string(255)
 *  
 * @package    orangehrm
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseFingerspotDevices extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ohrm_devices');
        $this->hasColumn('No', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('server_IP', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('server_port', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('device_sn', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}