<?php

/**
 * BaseFingerspotRecordTemp
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string                $sn                        Type: string(32), primary key
 * @property string                $scan_date                 Type: datetime, primary key, Date and time in ISO-8601 format (YYYY-MM-DD HH:MI)
 * @property string                $pin                       Type: string(30), primary key
 * @property int                   $verifymode                Type: integer
 * @property int                   $iomode                    Type: integer
 * @property int                   $workcode                  Type: integer
 * @property Employee              $Employee                  
 *  
 * @method string                  getSn()                    Type: string(32), primary key
 * @method string                  getScanDate()              Type: datetime, primary key, Date and time in ISO-8601 format (YYYY-MM-DD HH:MI)
 * @method string                  getPin()                   Type: string(30), primary key
 * @method int                     getVerifymode()            Type: integer
 * @method int                     getIomode()                Type: integer
 * @method int                     getWorkcode()              Type: integer
 * @method Employee                getEmployee()              
 *  
 * @method FingerspotRecordTemp    setSn(string $val)         Type: string(32), primary key
 * @method FingerspotRecordTemp    setScanDate(string $val)   Type: datetime, primary key, Date and time in ISO-8601 format (YYYY-MM-DD HH:MI)
 * @method FingerspotRecordTemp    setPin(string $val)        Type: string(30), primary key
 * @method FingerspotRecordTemp    setVerifymode(int $val)    Type: integer
 * @method FingerspotRecordTemp    setIomode(int $val)        Type: integer
 * @method FingerspotRecordTemp    setWorkcode(int $val)      Type: integer
 * @method FingerspotRecordTemp    setEmployee(Employee $val) 
 *  
 * @package    orangehrm
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseFingerspotRecordTemp extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ohrm_att_log_tmp');
        $this->hasColumn('sn', 'string', 32, array(
             'type' => 'string',
             'primary' => true,
             'length' => 32,
             ));
        $this->hasColumn('scan_date', 'datetime', null, array(
             'type' => 'datetime',
             'primary' => true,
             ));
        $this->hasColumn('pin', 'string', 30, array(
             'type' => 'string',
             'primary' => true,
             'length' => 30,
             ));
        $this->hasColumn('verifymode', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('iomode', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('workcode', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Employee', array(
             'local' => 'pin',
             'foreign' => 'pin'));
    }
}