<?php

/**
 * PluginCustomRecruitmentCandidateAttachmentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginCustomRecruitmentCandidateAttachmentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return PluginCustomRecruitmentCandidateAttachmentTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginCustomRecruitmentCandidateAttachment');
    }
}