<?php

/**
 * PluginCustomRecruitmentCandidateAttachment
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 *  
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PluginCustomRecruitmentCandidateAttachment extends BaseCustomRecruitmentCandidateAttachment
{
    private $date_ymd = '';

    public function setdate_ymd($date_ymd) {
        
       $this->date_ymd = $date_ymd;
    }
    public function getdate_ymd(){
        $ymdDate ='';
        if($this->getUploadDate() != null && $this->getUploadDate() != '---' )
        {
            $ymdDate = date('Y-m-d', strtotime($this->getUploadDate()));    
        }
        return  $ymdDate;
    }
}