<?php

/**
 * BaseCustomRecruitmentCandidateAttachment
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property int                                   $id                             Type: integer(13), primary key
 * @property string                                $vacancy_position               Type: string(50)
 * @property string                                $fileName                       Type: string(255)
 * @property string                                $fileType                       Type: string(255)
 * @property int                                   $fileSize                       Type: integer(30)
 * @property object                                $fileContent                    Type: blob(2147483647)
 * @property int                                   $attachmentType                 Type: integer(4)
 *  
 * @method int                                     getId()                         Type: integer(13), primary key
 * @method string                                  getVacancyPosition()            Type: string(50)
 * @method string                                  getFilename()                   Type: string(255)
 * @method string                                  getFiletype()                   Type: string(255)
 * @method int                                     getFilesize()                   Type: integer(30)
 * @method object                                  getFilecontent()                Type: blob(2147483647)
 * @method int                                     getAttachmenttype()             Type: integer(4)
 *  
 * @method CustomRecruitmentCandidateAttachment    setId(int $val)                 Type: integer(13), primary key
 * @method CustomRecruitmentCandidateAttachment    setVacancyPosition(string $val) Type: string(50)
 * @method CustomRecruitmentCandidateAttachment    setFilename(string $val)        Type: string(255)
 * @method CustomRecruitmentCandidateAttachment    setFiletype(string $val)        Type: string(255)
 * @method CustomRecruitmentCandidateAttachment    setFilesize(int $val)           Type: integer(30)
 * @method CustomRecruitmentCandidateAttachment    setFilecontent(object $val)     Type: blob(2147483647)
 * @method CustomRecruitmentCandidateAttachment    setAttachmenttype(int $val)     Type: integer(4)
 *  
 * @package    orangehrm
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCustomRecruitmentCandidateAttachment extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ohrm_custom_recruitment_candidate_attachment');
        $this->hasColumn('id', 'integer', 13, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 13,
             ));
        $this->hasColumn('vacancy_position', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('file_name as fileName', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('file_type as fileType', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('file_size as fileSize', 'integer', 30, array(
             'type' => 'integer',
             'length' => 30,
             ));
        $this->hasColumn('file_content as fileContent', 'blob', 2147483647, array(
             'type' => 'blob',
             'length' => 2147483647,
             ));
        $this->hasColumn('attachment_type as attachmentType', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}