<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2020/10/07 10:21:39

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=orangehrm_mysql;charset=utf8mb4',
  'username' => 'root',
  'password' => 'Polowijo605421',
  'attributes' => 
  array (
    'export' => 'tables',
  ),
  'name' => 'doctrine',
)),);
