<?php

/**
 * EmpContractNewTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EmpContractNewTable extends PluginEmpContractTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object EmpContractNewTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EmpContractNew');
    }
}