<?php

/**
 * PluginAttendanceRecordTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginFingerspotRecordTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginAttendanceRecordTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginFingerspotRecord');
    }
}

class PluginFingerspotRecordTempTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginAttendanceRecordTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginFingerspotRecordTemp');
    }
}


class PluginFingerspotDevicesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginAttendanceRecordTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginFingerspotDevices');
    }
}
?>