<?php

/**
 * PluginFingerspotRecordTempTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginFingerspotRecordTempTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return PluginFingerspotRecordTempTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginFingerspotRecordTemp');
    }
}