<?php

/**
 * PluginFingerspotDevicesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginFingerspotDevicesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return PluginFingerspotDevicesTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginFingerspotDevices');
    }
}