<?php

/**
 * CustomRecruitmentCandidateAttachmentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CustomRecruitmentCandidateAttachmentTable extends PluginCustomRecruitmentCandidateAttachmentTable
{
    /**
     * Returns an instance of this class.
     *
     * @return CustomRecruitmentCandidateAttachmentTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CustomRecruitmentCandidateAttachment');
    }
}